In [1]:
import pandas as pd

In [3]:
mapped_disease = pd.read_csv("./data/linked_to_ontologies/mapped_clinical_data_disease_cleaned_with_mondo_parents.csv")[['nct_id','disease_term_mondo_clean','merged_mondo_label']]

In [4]:
mapped_disease.head()

,nct_id,disease_term_mondo_clean,merged_mondo_label
0,NCT00000114,retinitis pigmentosa,retinitis pigmentosa
1,NCT00000102,adrenogenital syndrome,adrenogenital syndrome
2,NCT00000113,myopia|myopia 6,myopia|myopia 6
3,NCT00000115,cystoid macular edema|uveitis-associated,cystoid macular edema|uveitis-associated|macul...
4,NCT00000117,optic neuritis|multiple sclerosis,optic neuritis|multiple sclerosis

In [5]:
mapped_disease[mapped_disease['disease_term_mondo_clean'].str.contains("relapsing-remitting")].to_csv("data/check_MS_parents.csv", index=False)

In [6]:
mapped_disease.shape

(293949, 3)

In [8]:
pd.read_csv("./data/raw_aact/mv_interventional_drug_studies_20260302.csv").shape

(293949, 11)

In [18]:
raw_aact = pd.read_csv("./data/raw_aact/mv_interventional_drug_studies_20260302.csv")
raw_aact.shape

(293949, 12)

In [19]:
raw_aact

,nct_id,brief_title,study_official_title,start_date,completion_date,study_first_submitted_date,phase,overall_status,brief_summary,intervention_names,intervention_types,condition_names
0,NCT00005972,Combination Chemotherapy in Treating Patients ...,Phase II Trial of Gemcitabine/Irinotecan as Se...,2000-05-31,2008-02-29,2000-07-05,PHASE2,COMPLETED,RATIONALE: Drugs used in chemotherapy use diff...,gemcitabine hydrochloride | irinotecan hydroch...,DRUG,Lung Cancer
1,NCT00005977,Combination Chemotherapy in Treating Patients ...,A Pilot Study of Dose Intensification of Metho...,2000-09-30,2006-09-30,2000-07-05,PHASE3,COMPLETED,RATIONALE: Drugs used in chemotherapy use diff...,cyclophosphamide | cytarabine | dexamethasone ...,BIOLOGICAL | DRUG,Leukemia | Lymphoma
2,NCT00005981,Combination Chemotherapy in Treating Patients ...,Phase II Trial of O6Benzylguanine and BCNU in ...,2000-06-30,2003-11-30,2000-07-05,PHASE2,COMPLETED,RATIONALE: Drugs used in chemotherapy use diff...,O6-benzylguanine | carmustine,DRUG,Colorectal Cancer
3,NCT00005984,Cyclophosphamide and Filgrastim Followed By SC...,Autologous Marrow Transplantation for Chronic ...,2000-08-31,2005-09-30,2000-07-05,PHASE2,TERMINATED,"RATIONALE: Giving colony-stimulating factors, ...",cyclophosphamide | filgrastim | recombinant in...,DRUG,Leukemia
4,NCT00005986,"Chemotherapy, Filgrastim and Peripheral Stem C...",Autologous Transplantation for Chronic Myeloge...,2000-08-31,NaN,2000-07-05,PHASE2,TERMINATED,RATIONALE: Drugs used in chemotherapy use diff...,busulfan | cyclophosphamide | filgrastim | rec...,DRUG,Leukemia
...,...,...,...,...,...,...,...,...,...,...,...,...
293944,NCT00005961,O6-benzylguanine and Carmustine in Treating Pa...,A Phase II Trial of O6-Benzylguanine (NSC 6370...,2000-06-30,NaN,2000-07-05,PHASE2,COMPLETED,Phase II trial to study the effectiveness of O...,O6-benzylguanine | carmustine,DRUG,Melanoma (Skin)
293945,NCT00005962,Comparison of Three Treatment Regimens in Trea...,A Phase II Randomized Trial of Immunologic and...,2000-10-04,2007-06-30,2000-07-05,PHASE2,COMPLETED,RATIONALE: Drugs used in chemotherapy use diff...,cyclophosphamide | cytarabine | gemtuzumab ozo...,BIOLOGICAL | DRUG,Leukemia
293946,NCT00005964,Comparison of Two Combination Chemotherapy Reg...,Randomized Phase II Study of Dose-Adjusted EPO...,2000-05-31,2006-03-31,2000-07-05,PHASE2,COMPLETED,RATIONALE: Drugs used in chemotherapy use diff...,cyclophosphamide | doxorubicin hydrochloride |...,BIOLOGICAL | DRUG,Lymphoma
293947,NCT00005966,Interferon Alfa-2b With or Without Thalidomide...,Phase III Randomized Trial of Interferon-Alfa2...,2000-10-31,NaN,2000-07-05,PHASE3,COMPLETED,RATIONALE: Interferon alfa-2b may interfere wi...,recombinant interferon alfa | thalidomide,BIOLOGICAL | DRUG,Kidney Cancer
293948,NCT00005967,Tipifarnib in Treating Patients With Advanced ...,A Dose Finding Study of R115777 (NSC 702818) i...,2000-08-31,NaN,2000-07-05,PHASE1,COMPLETED,Randomized phase I trial to study the effectiv...,tipifarnib,DRUG,Chronic Myeloproliferative Disorders | Leukemi...

In [21]:
raw_aact[
    raw_aact['intervention_names'].str.contains("exercise", case=False, na=False)
]

,nct_id,brief_title,study_official_title,start_date,completion_date,study_first_submitted_date,phase,overall_status,brief_summary,intervention_names,intervention_types,condition_names
1822,NCT00037934,Robotic Upper-Limb Neurorehabilitation in Chro...,Evaluation of Robotic Upper Extremity Neuro-Re...,2002-04-30,2004-12-31,2002-05-24,PHASE2,COMPLETED,We have established the feasibility and effect...,Traditional Supervised Upper Extremity Exercises,OTHER,Stroke
3465,NCT00068458,Survival TRaining for ENhancing Total Health (...,A Phase II Randomized Study to Assess the Feas...,2003-09-30,2005-01-31,2003-09-10,PHASE2,COMPLETED,RATIONALE: A home-based exercise and/or diet p...,Arm 2: Exercise + Calcium-Rich Diet | Calcium-...,DIETARY_SUPPLEMENT | OTHER,Breast Cancer | Depression | Weight Changes
3963,NCT00078624,Knee Stability Training for Knee Osteoarthriti...,Knee Stability Training in Individuals With Kn...,2004-04-30,2008-12-31,2004-03-03,PHASE2,COMPLETED,People with knee osteoarthritis (OA) frequentl...,Knee stability training | Traditional exercise...,OTHER,Joint Diseases | Osteoarthritis
4355,NCT00085722,Joint Injections for Osteoarthritic Knee Pain,The Efficacy of Prolotherapy in Osteoarthritic...,2004-07-31,2016-05-01,2004-06-14,PHASE1/PHASE2,COMPLETED,The purpose of this study is to determine whet...,At-home physical therapy exercise group,OTHER,Osteoarthritis
4683,NCT00090961,"S0229, Pulmonary Rehabilitation Education w/wo...",A Randomized Trial Assessing the Effects of Ex...,2004-09-30,2008-10-31,2004-09-07,NaN,TERMINATED,RATIONALE: Pulmonary rehabilitation education ...,educational intervention | supervised exercise...,OTHER,Lung Cancer | Pulmonary Complications
...,...,...,...,...,...,...,...,...,...,...,...,...
290291,NCT07253870,Comperative Effects of Transcutaneous Auricula...,Comparative Effects of Transcutaneous Auricula...,2025-11-20,2026-05-20,2025-11-19,NaN,NOT_YET_RECRUITING,This study aims to determine whether transcuta...,Transcutaneous vagus nerve stimulation through...,OTHER,"Stroke | Stroke, Acute"
290297,NCT07254273,Boccia Exercises and Upper Limb Muscle Adaptat...,Effects of Boccia Exercises on Upper Extremity...,2024-10-24,2025-01-20,2025-11-13,NaN,COMPLETED,This study investigates whether adding Boccia ...,Boccia exercise | physiotherapy,OTHER,Hemiparesis After Stroke
290299,NCT07254377,Design and Validation of Innovative Strategies...,START: Design and Validation of Innovative Str...,2025-11-01,2027-02-28,2025-11-19,NaN,ACTIVE_NOT_RECRUITING,"People affected by Stroke, Multiple Sclerosis ...",DT exercise | Physical therapy,OTHER,Dual Task Exercises
290310,NCT07254793,Prophylactic and Therapeutic DLI-X for Leukemi...,A Feasibility/Pilot First-in-human Study of Ex...,2026-02-28,2030-06-01,2025-11-19,PHASE1,NOT_YET_RECRUITING,The primary objective of this proposal is to c...,Exercise Mobilized Prophylactic DLI | Exercise...,BIOLOGICAL,Acute Lymphoid Leukemia | Acute Myeloid Leukem...
293702,NCT00005137,"Heritage Study--Genetics, Exercise and Risk Fa...","Health, Risk Factors, Exercise Training, and G...",1992-07-31,2005-08-31,2000-05-25,NaN,COMPLETED,To document the role of the genotype in the ca...,exercise program,OTHER,Cardiovascular Diseases | Diabetes Mellitus | ...

In [9]:
pd.read_csv("./data/raw_aact/mv_interventional_drug_studies_20260222_neuro.csv").shape

(77874, 11)

In [46]:
test = pd.read_csv("./data/aact_with_ner_for_linking/aact_with_ner.csv")

In [48]:
test[
    test['merged_drug_names'].str.contains("exercise", case=False, na=False)
]

,nct_id,intervention_types,aact_drug_names,aact_condition_names,ner_predicted_drugs,ner_predicted_conditions,merged_drug_names,merged_condition_names
10126,NCT00204425,DIETARY_SUPPLEMENT,exercise/soy isoflavone,Osteopenia | Osteoporosis,isoflavone | soy-based nutritional supplement ...,osteoporosis,exercise/soy isoflavone | isoflavone | soy-bas...,Osteopenia | Osteoporosis
12235,NCT00249704,DRUG,Vitamin D + Exercise | Vitamin D + Sham Exercise,"Elderly, Frail",vitamin d,falls | frail,Vitamin D | Exercise | Sham Exercise,"Elderly, Frail | falls | frail"
23174,NCT00478972,DRUG | OTHER,Diet and exercise | Rimonabant | placebo (for ...,Diabetes Mellitus Type 2 | Obesity,rimonabant | sr141716,obese type 2 diabetic,Diet | exercise | Rimonabant | placebo (for Ri...,Diabetes Mellitus Type | Obesity | obese type ...
23729,NCT00492661,DRUG,Tacrolimus With Diet and Exercise Intervention,Kidney Transplantion | Renal Transplantion,prograf | tacrolimus,de novo renal transplant recipients | insulin ...,Tacrolimus With Diet | Exercise Intervention |...,Kidney Transplantion | Renal Transplantion | d...
23923,NCT00496964,DRUG,Botulinum toxin A + exercise | Placebo,Patellofemoral Pain Syndrome,botox release | botulinum toxin | botulinum to...,knee pain | patellofemoral pain | patellofemor...,Botulinum toxin A | exercise | Placebo | botox...,Patellofemoral Pain Syndrome | knee pain | pat...
...,...,...,...,...,...,...,...,...
212017,NCT06975345,DRUG | OTHER,Medical treatment. | Multicomponent interventi...,"Low Back Pain, Mechanical | Musculoskeletal Ma...",Medical treatment. | Multicomponent interventi...,"chronic , mechanical , non-specific low back p...",Medical treatment. | Multicomponent interventi...,"Low Back Pain, Mechanical | Musculoskeletal Ma..."
212202,NCT07007858,OTHER,Exercise,Cerebral Palsy (CP) | Spastic Diplegia Cerebra...,bont-a,cerebral palsy | spastic | spastic cerebral pa...,Exercise | bont-a,Cerebral Palsy (CP) | Spastic Diplegia Cerebra...
212882,NCT07101653,OTHER,Exercise,Multiple Sclerosis,iris,multiple sclerosis,Exercise | iris,Multiple Sclerosis
213369,NCT07175740,DIETARY_SUPPLEMENT | OTHER,Aspartame enriched meal | Exercise session | F...,Glycemic Response | Type 2 Diabetes,aspartame | fat | fructose | glucose meal,type 2 diabetes | type 2 diabetics,Aspartame enriched meal | Exercise session | F...,Glycemic Response | Type Diabetes | type diabe...
213937,NCT07254793,BIOLOGICAL,Exercise Mobilized Prophylactic DLI | Exercise...,Acute Lymphoid Leukemia | Acute Myeloid Leukem...,blinatumomab | blinatumomab leukemia,allogeneic hematopoietic cell transplantation ...,Exercise Mobilized Prophylactic DLI | Exercise...,Acute Lymphoid Leukemia | Acute Myeloid Leukem...

In [49]:
test[
    test['merged_condition_names'].str.contains("zika", case=False, na=False)
]

,nct_id,intervention_types,aact_drug_names,aact_condition_names,ner_predicted_drugs,ner_predicted_conditions,merged_drug_names,merged_condition_names
99726,NCT02809443,BIOLOGICAL,GLS-5700,Healthy,gls-5700 | gls-5700 plasmid,dengue virus | zik | zika virus,GLS | gls- plasmid,Healthy | dengue virus | zik | zika virus
102650,NCT02937233,BIOLOGICAL | OTHER,Placebo | Zika Virus Purified Inactivated Vaccine,Zika,alum adjuvant | zika virus purified inactivate...,Zika,Placebo | Zika Virus Purified Inactivated Vacc...,Zika
107359,NCT03110770,BIOLOGICAL | OTHER,VRC-PBSPLA043-00-VP | VRC-ZKADNA090-00-VP,Flaviviral Diseases | Flaviviridae Infections ...,vrc-zkadna090-00-vp | zika virus dna vaccine |...,Flaviviral Diseases | Flaviviridae Infections ...,VRC-PBSPLA043--VP | VRC-ZKADNA090--VP | zika v...,Flaviviral Diseases | Flaviviridae Infections ...
107443,NCT03116802,DRUG,Stamaril (live attenuated yellow fever vaccine),Yellow Fever | Yellow Fever Vaccine,anti-inflammatory therapy | statins | statins ...,ebola | measles | metabolic disorders | polio ...,Stamaril (live attenuated yellow fever vaccine...,Yellow Fever | Yellow Fever Vaccine | ebola | ...
118009,NCT03553277,OTHER,placebo | transfluthrin,Arbovirus Infections,transfluthrin,aedes-borne dengue | aedes-borne virus | aedes...,placebo | transfluthrin,Arbovirus Infections | aedes-borne dengue | ae...
127982,NCT02840487,BIOLOGICAL,VRC-ZKADNA085-00-VP,Prevention of Zika Infection | Zika-Specific I...,zika virus dna vaccine,guillain-barr (sqrroot) (copyright syndrome | ...,VRC-ZKADNA085--VP | zika virus dna vaccine,Prevention of Zika Infection | Zika-Specific I...
128798,NCT04015648,BIOLOGICAL,ChAdOx1 Zika,Zika,chadox1 zika | chadox1 zika vaccine | zika vir...,Zika,ChAdOx1 Zika | chadox1 zika vaccine | zika vir...,Zika
129402,NCT02887482,BIOLOGICAL,GLS-5700 | Placebo,Healthy | Zika,gls-5700 | gls-5700 plasmid vaccine,dengue virus - | zika virus,GLS | Placebo | gls- plasmid vaccine,Healthy | Zika | dengue virus | zika virus
129942,NCT04064905,BIOLOGICAL | OTHER,Placebo | mRNA-1893,Zika Virus,mrna-1893 | zika vaccine | zika vaccines,flavivirus | flavivirus seropositive,Placebo | mRNA | zika vaccine | zika vaccines,Zika Virus | flavivirus | flavivirus seropositive
131513,NCT02952833,BIOLOGICAL | DRUG,Saline | Zika Virus Purified Inactivated Vacci...,Zika Virus Infection,alum adjuvanted | zika virus purified inactiva...,flavivirus | zikv,Saline | Zika Virus Purified Inactivated Vacci...,Zika Virus Infection | flavivirus | zikv
132051,NCT02963909,BIOLOGICAL | OTHER,IXIARO | Placebo | YF Vax 17D Strain | Zika Vi...,Zika Virus Infection,alum adjuvanted | ixiaro® | yf-vax | zika viru...,flavivirus | flavivirus-naive | flavivirus-pri...,IXIARO | Placebo | YF Vax 17D Strain | Zika Vi...,Zika Virus Infection | flavivirus | flavivirus...
133070,NCT02996461,BIOLOGICAL,VRC-ZKADNA090-00-VP,Prevention of Zika Infection | Zika-Specific I...,vrc-zkadna090-00-vp | zika virus dna vaccine,zika infection | zika virus | zika virus disease,VRC-ZKADNA090--VP | zika virus dna vaccine,Prevention of Zika Infection | Zika-Specific I...
133100,NCT02996890,BIOLOGICAL | OTHER,MV-ZIKA | Placebo,Zika Virus,mv-zika,zika virus,MV-ZIKA | Placebo,Zika Virus
133611,NCT03008122,BIOLOGICAL | OTHER,Placebo | Zika Virus Purified Inactivated Vacc...,Zika Virus Infection,alum adjuvanted | zika virus purified inactiva...,flav,Placebo | Zika Virus Purified Inactivated Vacc...,Zika Virus Infection | flav
133857,NCT03014089,BIOLOGICAL | OTHER,Placebo | mRNA-1325,Zika Virus,mrna 1325 | mrna-1325 | zika vaccine,zika,Placebo | mRNA | zika vaccine,Zika Virus | zika
138084,NCT04440774,BIOLOGICAL,CHIK high dose | CHIK low dose | CHIK mid dose...,Chikungunya | Zika,chadox1 chik | chadox1 zika | chadox1 zika vac...,chikungunya vaccine,CHIK high dose | CHIK low dose | CHIK mid dose...,Chikungunya | Zika | chikungunya vaccine
144954,NCT03343626,BIOLOGICAL | DRUG,PIZV | Placebo,Flavivirus Infections | Healthy Participants |...,purified inactivated zika virus vaccine,flavivirus | flavivirus naive primed,PIZV | Placebo | purified inactivated zika vir...,Flavivirus Infections | Healthy Participants |...
147697,NCT03425149,BIOLOGICAL,Placebo | VLA1601,Zika Virus | Zika Virus Infection,alum adjuvanted inactivated whole zika virus v...,flavivirus,Placebo | VLA1601 | alum adjuvanted inactivate...,Zika Virus | Zika Virus Infection | flavivirus
148146,NCT03443830,DRUG,Tyzivumab,Treatment of Acute Zika Virus Infection,mab | tyzivumab | zikv monoclonal antibody,zika virus | zikv infection,Tyzivumab | mab | zikv monoclonal antibody,Treatment of Acute Zika Virus Infection | zika...
148768,NCT04917861,BIOLOGICAL,Placebo | mRNA-1893,Zika Virus,mrna-1893 | zika vaccine,Zika Virus,Placebo | mRNA | zika vaccine,Zika Virus
153915,NCT03611946,BIOLOGICAL,Single dose of placebo via subcutaneous inject...,Zika Virus,rzikv/d4δ30-713 | zika vaccine,flavivirus,Single dose of placebo via subcutaneous inject...,Zika Virus | flavivirus
154301,NCT03624946,BIOLOGICAL | OTHER,Placebo | Zika Virus Immune Globulin (ZIKV-IG),Zika Virus Disease | Zika Virus Infection,zika virus immune globulin,zika virus infection,Placebo | Zika Virus Immune Globulin (ZIKV-IG)...,Zika Virus Disease | Zika Virus Infection
158604,NCT03776695,BIOLOGICAL | OTHER,Placebo | Tyzivumab,Treatment of Acute Zika Virus Infection,mab | tyzivumab | zikv monoclonal antibody,acute zikv infected | zika virus | zikv infection,Placebo | Tyzivumab | mab | zikv monoclonal an...,Treatment of Acute Zika Virus Infection | acut...
158605,NCT03776786,BIOLOGICAL | OTHER,0.9% Saline | TY014,Treatment of Acute Yellow Fever Virus Infection,monoclonal antibody | ty014 | yfv monoclonal a...,dengue virus | yellow fever | yellow fever vir...,Saline | TY014 | monoclonal antibody | yfv mon...,Treatment of Acute Yellow Fever Virus Infectio...
160882,NCT05469802,BIOLOGICAL | OTHER,Placebo | Purified Inactivated Zika Virus Vacc...,Healthy Volunteers,purified inactivated zika virus vaccine,zika,Placebo | Purified Inactivated Zika Virus Vacc...,Healthy Volunteers | zika
166390,NCT04033068,BIOLOGICAL | OTHER,One MV-ZIKA-RSP vaccination (high dose) and on...,Zika Virus Infection,mv-zika-rsp,Zika Virus Infection,One MV-ZIKA-RSP vaccination (high dose) | one ...,Zika Virus Infection
176666,NCT06268691,OTHER,Insecticide Coating INESFLY,Arbovirus Infections | Chikungunya Fever | Den...,alphacypermertrin acm | insect growth regulato...,dengue,Insecticide Coating INESFLY | alphacypermertri...,Arbovirus Infections | Chikungunya Fever | Den...
176734,NCT04371822,DRUG | OTHER,SnPP Protoporphyrin plus Sunlight exposure | S...,COVID-19,"2 , 6-difluoro-meso-tetraphenylporphine | co p...",acquired acute porphyria | chikun | chikv | co...,SnPP Protoporphyrin plus Sunlight exposure | S...,COVID | acquired acute porphyria | chikun | ch...
177941,NCT06334393,BIOLOGICAL,3M-052-AF | CpG 1018® | VLA1601,Zika | Zika Virus Infection,"3m-052-af | ap 60-70 | cpg1018 | inactivated ,...",flav,3M--AF | CpG ® | VLA1601 | ap | cpg1018 | inac...,Zika | Zika Virus Infection | flav
179599,NCT04478656,BIOLOGICAL,BBV121,Zika Virus Infection,bbv121 | purified inactivated adsorbed zika vi...,dengue sero-negative | dengue sero-positive,BBV121 | purified inactivated adsorbed zika vi...,Zika Virus Infection | dengue sero-negative | ...
210744,NCT06805487,BIOLOGICAL,Challenge virus ZIKV-SJRP/2016-184 | Plasmalyt...,Zika Virus,dengue vaccine | tetravalent | tv003 | tv003 d...,zika infection | zika virus | zikv sjrp | zikv...,Challenge virus ZIKV-SJRP/ | Plasmalyte | Tetr...,Zika Virus | zika infection | zikv sjrp | zikv...

In [33]:
test['ner_predicted_drugs'].isna().sum()

np.int64(0)

In [34]:
test[test['ner_predicted_drugs'].isna()]

Empty DataFrame
Columns: [nct_id, aact_drug_names, aact_condition_names, ner_predicted_drugs, ner_predicted_conditions, merged_drug_names, merged_condition_names]
Index: []

In [35]:
test[test['ner_predicted_conditions'].isna()]

Empty DataFrame
Columns: [nct_id, aact_drug_names, aact_condition_names, ner_predicted_drugs, ner_predicted_conditions, merged_drug_names, merged_condition_names]
Index: []

In [36]:
test[
    test['ner_predicted_drugs'].isna() &
    test['ner_predicted_conditions'].isna()
]

Empty DataFrame
Columns: [nct_id, aact_drug_names, aact_condition_names, ner_predicted_drugs, ner_predicted_conditions, merged_drug_names, merged_condition_names]
Index: []

In [38]:
empty_drug_df = pd.read_csv("./data/aact_with_ner_for_linking/rows_with_empty_pred_drug.csv")

In [39]:
empty_drug_df

,nct_id,aact_drug_names,aact_condition_names,ner_predicted_drugs,ner_predicted_conditions,merged_drug_names,merged_condition_names
0,NCT00000149,Beta Blocker,Open-Angle Glaucoma,NaN,glaucoma | newly diagnosed open-angle glaucoma,Beta Blocker,Open-Angle Glaucoma | glaucoma | newly diagnos...
1,NCT00000268,Bupropion,Cocaine-Related Disorders,NaN,attention deficit disorder | cocaine,Bupropion,Cocaine-Related Disorders | attention deficit ...
2,NCT00000308,D-amphetamine | Dextroamphetamine | placebo,Cocaine-Related Disorders,NaN,cocaine dependent,D-amphetamine | Dextroamphetamine | placebo,Cocaine-Related Disorders | cocaine dependent
3,NCT00000313,Fenfluramine,Cocaine-Related Disorders,NaN,serotonergic alterations,Fenfluramine,Cocaine-Related Disorders | serotonergic alter...
4,NCT00000399,Hormone replacement therapy,Osteoporosis,NaN,osteoporosis,Hormone replacement therapy,Osteoporosis
...,...,...,...,...,...,...,...
83830,NCT00000526,encainide | flecainide | moricizine,Cardiovascular Diseases | Coronary Disease | D...,NaN,asymptomatic ventricular arrhythmias | cardiac...,encainide | flecainide | moricizine,Cardiovascular Diseases | Coronary Disease | D...
83831,NCT00000530,nifedipine,Cardiovascular Diseases | Heart Diseases | Ray...,NaN,attacks | raynaud ' | raynaud's syndrome | vas...,nifedipine,Cardiovascular Diseases | Heart Diseases | Ray...
83832,NCT00000552,thrombolytic therapy,Cardiovascular Diseases | Coronary Disease | H...,NaN,cardiogenic shock | cardiogenic shock revascul...,thrombolytic therapy,Cardiovascular Diseases | Coronary Disease | H...
83833,NCT00000620,Anti-hyperglycemic Agents | Anti-hypertensive ...,Atherosclerosis | Cardiovascular Diseases | Co...,NaN,diabetes | heart | type 2 diabetes mellitus,Anti-hyperglycemic Agents | Anti-hypertensive ...,Atherosclerosis | Cardiovascular Diseases | Co...
83834,NCT00000125,Topical ocular hypotensive eye drops.,Glaucoma | Ocular Hypertension,NaN,glaucomatous visual field loss damage | ocular...,Topical ocular hypotensive eye drops.,Glaucoma | Ocular Hypertension | glaucomatous ...

In [40]:
aact = pd.read_csv("./data/raw_aact/mv_interventional_drug_studies_20260302.csv")

In [43]:
empty_drug_df = empty_drug_df.merge(aact[['nct_id','intervention_names','intervention_types']],on="nct_id",how="left")

In [44]:
empty_drug_df

,nct_id,aact_drug_names,aact_condition_names,ner_predicted_drugs,ner_predicted_conditions,merged_drug_names,merged_condition_names,intervention_names,intervention_types
0,NCT00000149,Beta Blocker,Open-Angle Glaucoma,NaN,glaucoma | newly diagnosed open-angle glaucoma,Beta Blocker,Open-Angle Glaucoma | glaucoma | newly diagnos...,Beta Blocker,DRUG
1,NCT00000268,Bupropion,Cocaine-Related Disorders,NaN,attention deficit disorder | cocaine,Bupropion,Cocaine-Related Disorders | attention deficit ...,Bupropion,DRUG
2,NCT00000308,D-amphetamine | Dextroamphetamine | placebo,Cocaine-Related Disorders,NaN,cocaine dependent,D-amphetamine | Dextroamphetamine | placebo,Cocaine-Related Disorders | cocaine dependent,D-amphetamine | Dextroamphetamine | placebo,DRUG
3,NCT00000313,Fenfluramine,Cocaine-Related Disorders,NaN,serotonergic alterations,Fenfluramine,Cocaine-Related Disorders | serotonergic alter...,Fenfluramine,DRUG
4,NCT00000399,Hormone replacement therapy,Osteoporosis,NaN,osteoporosis,Hormone replacement therapy,Osteoporosis,Hormone replacement therapy,DRUG
...,...,...,...,...,...,...,...,...,...
83830,NCT00000526,encainide | flecainide | moricizine,Cardiovascular Diseases | Coronary Disease | D...,NaN,asymptomatic ventricular arrhythmias | cardiac...,encainide | flecainide | moricizine,Cardiovascular Diseases | Coronary Disease | D...,encainide | flecainide | moricizine,DRUG
83831,NCT00000530,nifedipine,Cardiovascular Diseases | Heart Diseases | Ray...,NaN,attacks | raynaud ' | raynaud's syndrome | vas...,nifedipine,Cardiovascular Diseases | Heart Diseases | Ray...,nifedipine,DRUG
83832,NCT00000552,thrombolytic therapy,Cardiovascular Diseases | Coronary Disease | H...,NaN,cardiogenic shock | cardiogenic shock revascul...,thrombolytic therapy,Cardiovascular Diseases | Coronary Disease | H...,thrombolytic therapy,DRUG
83833,NCT00000620,Anti-hyperglycemic Agents | Anti-hypertensive ...,Atherosclerosis | Cardiovascular Diseases | Co...,NaN,diabetes | heart | type 2 diabetes mellitus,Anti-hyperglycemic Agents | Anti-hypertensive ...,Atherosclerosis | Cardiovascular Diseases | Co...,Anti-hyperglycemic Agents | Anti-hypertensive ...,DRUG
83834,NCT00000125,Topical ocular hypotensive eye drops.,Glaucoma | Ocular Hypertension,NaN,glaucomatous visual field loss damage | ocular...,Topical ocular hypotensive eye drops.,Glaucoma | Ocular Hypertension | glaucomatous ...,Topical ocular hypotensive eye drops.,DRUG

In [45]:
empty_drug_df[
    empty_drug_df['intervention_types'].str.contains("DRUG", case=False, na=False)
]

,nct_id,aact_drug_names,aact_condition_names,ner_predicted_drugs,ner_predicted_conditions,merged_drug_names,merged_condition_names,intervention_names,intervention_types
0,NCT00000149,Beta Blocker,Open-Angle Glaucoma,NaN,glaucoma | newly diagnosed open-angle glaucoma,Beta Blocker,Open-Angle Glaucoma | glaucoma | newly diagnos...,Beta Blocker,DRUG
1,NCT00000268,Bupropion,Cocaine-Related Disorders,NaN,attention deficit disorder | cocaine,Bupropion,Cocaine-Related Disorders | attention deficit ...,Bupropion,DRUG
2,NCT00000308,D-amphetamine | Dextroamphetamine | placebo,Cocaine-Related Disorders,NaN,cocaine dependent,D-amphetamine | Dextroamphetamine | placebo,Cocaine-Related Disorders | cocaine dependent,D-amphetamine | Dextroamphetamine | placebo,DRUG
3,NCT00000313,Fenfluramine,Cocaine-Related Disorders,NaN,serotonergic alterations,Fenfluramine,Cocaine-Related Disorders | serotonergic alter...,Fenfluramine,DRUG
4,NCT00000399,Hormone replacement therapy,Osteoporosis,NaN,osteoporosis,Hormone replacement therapy,Osteoporosis,Hormone replacement therapy,DRUG
...,...,...,...,...,...,...,...,...,...
83830,NCT00000526,encainide | flecainide | moricizine,Cardiovascular Diseases | Coronary Disease | D...,NaN,asymptomatic ventricular arrhythmias | cardiac...,encainide | flecainide | moricizine,Cardiovascular Diseases | Coronary Disease | D...,encainide | flecainide | moricizine,DRUG
83831,NCT00000530,nifedipine,Cardiovascular Diseases | Heart Diseases | Ray...,NaN,attacks | raynaud ' | raynaud's syndrome | vas...,nifedipine,Cardiovascular Diseases | Heart Diseases | Ray...,nifedipine,DRUG
83832,NCT00000552,thrombolytic therapy,Cardiovascular Diseases | Coronary Disease | H...,NaN,cardiogenic shock | cardiogenic shock revascul...,thrombolytic therapy,Cardiovascular Diseases | Coronary Disease | H...,thrombolytic therapy,DRUG
83833,NCT00000620,Anti-hyperglycemic Agents | Anti-hypertensive ...,Atherosclerosis | Cardiovascular Diseases | Co...,NaN,diabetes | heart | type 2 diabetes mellitus,Anti-hyperglycemic Agents | Anti-hypertensive ...,Atherosclerosis | Cardiovascular Diseases | Co...,Anti-hyperglycemic Agents | Anti-hypertensive ...,DRUG
83834,NCT00000125,Topical ocular hypotensive eye drops.,Glaucoma | Ocular Hypertension,NaN,glaucomatous visual field loss damage | ocular...,Topical ocular hypotensive eye drops.,Glaucoma | Ocular Hypertension | glaucomatous ...,Topical ocular hypotensive eye drops.,DRUG